#!/usr/bin/env bash

LATEST_VERSION="5"

if [ "$DOCKER_TAG" = "$LATEST_VERSION" ]; then
	DOCKER_TAG=latest
fi

if [ "$DOCKER_TAG" = "latest" ]; then
	docker build -t ${IMAGE_NAME} .
else
	## Fail if missing docker file
	docker build -t ${IMAGE_NAME} -f Dockerfile.${DOCKER_TAG} .
fi
