#!/usr/bin/env bash

LATEST_VERSION="5"

if [ "$DOCKER_TAG" = "$LATEST_VERSION" ]; then
	DOCKER_TAG=latest
fi

if [ "$DOCKER_TAG" = "latest" ]; then
	docker build -t ${IMAGE_NAME} .
else
	if [ -f "Dockerfile.${DOCKER_TAG}" ]; then
		docker build -t ${IMAGE_NAME} -f Dockerfile.${DOCKER_TAG} .
	else
		if [ "$DOCKER_TAG" = "6" ]; then
			docker build -t ${IMAGE_NAME} \
				--build-arg=BASE_IMAGE=stretch \
				--build-arg=PHPVERSION=7 \
				--build-arg=PHPCONF=/etc/php/7.0 \
				.
			docker build -t ${DOCKER_REPO}:6.1 \
				--build-arg=BASE_IMAGE=stretch \
				--build-arg=PHPVERSION=7 \
				--build-arg=PHPCONF=/etc/php/7.0 \
				.
		fi
	fi
fi
